# Generated by Django 4.2.3 on 2023-07-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('word_of_the_week', models.CharField(max_length=400)),
                ('wow_definition', models.TextField()),
                ('wow_example', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator_crutch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evcrutch', related_query_name='agenda_evcrutch', to='core.member')),
                ('evaluator_general', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evgeneral', related_query_name='agenda_evgeneral', to='core.member')),
                ('evaluator_grammar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evgrammar', related_query_name='agenda_evgrammar', to='core.member')),
                ('evaluator_pronunciation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='evpronunciation', related_query_name='agenda_evpronunciation', to='core.member')),
                ('evaluator_time', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evtime', related_query_name='agenda_evtime', to='core.member')),
                ('toastmaster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='toastmaster', related_query_name='agenda_toastmaster', to='core.member')),
            ],
        ),
    ]
