# Generated by Django 4.2.3 on 2023-07-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('education', '0002_agenda_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='time',
            field=models.TimeField(default='01:30:00.000'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='evaluator_crutch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evcrutch', related_query_name='agenda_evcrutch', to='core.member', verbose_name='Crutches'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='evaluator_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evgeneral', related_query_name='agenda_evgeneral', to='core.member', verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='evaluator_grammar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evgrammar', related_query_name='agenda_evgrammar', to='core.member', verbose_name='Grammar'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='evaluator_pronunciation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='evpronunciation', related_query_name='agenda_evpronunciation', to='core.member', verbose_name='Pronunciation'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='evaluator_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evtime', related_query_name='agenda_evtime', to='core.member', verbose_name='Timekeeper'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='wow_definition',
            field=models.TextField(verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='wow_example',
            field=models.TextField(verbose_name='Example'),
        ),
    ]
